ARG JDK_OS=17-focal
FROM docker.io/maven:3-eclipse-temurin-${JDK_OS}

RUN \
  apt-get update \
  && apt-get install -y \
    gzip \
    libswt-gtk-4-jni \
    python3 \
    tar \
    zip \
  && : # END
