default_language_version:
  python: python3

repos:
- repo: meta
  hooks:
  # Check that hooks listed actually do something
  - id: check-hooks-apply
  # Check that any excludes do indeed exclude something
  - id: check-useless-excludes

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks: []
  # Format all C/C++ code with Clang-format
  # - id: clang-format

- repo: https://github.com/psf/black
  rev: '22.6.0'
  hooks:
  # Blacken all Python code, except allow slightly longer line lengths
  - id: black
    args: ['--line-length=100']
    exclude: |
      (?x)^(
        scripts/cover2cover.py |    # This file is from an external source, don't format it
        edu.rice.cs.hpcdata.app/scripts/hpcread.py    # Not sure what this is used for yet
      )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # Remove any trailing whitespace
  # - id: trailing-whitespace
  # All files must end in a single newline (or be perfectly empty)
  # - id: end-of-file-fixer
  # Remove the UTF8 BOM from the start of any files
  - id: fix-byte-order-marker
  # Use UNIX-style line endings (lf)
  # - id: mixed-line-ending
  #   args: [--fix=lf]
  # Ensure all executable scripts have a shebang
  # - id: check-executables-have-shebangs
  # Ensure large files (>=500KB) are never added outside of LFS
  - id: check-added-large-files

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.3.0
  hooks: []
  # Scan for secrets that should never appear in the repo itself
  # - id: detect-secrets

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks: []
  # Find common errors in shell scripts using shellcheck
  # - id: shellcheck

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: '0.17.1'
  hooks:
  # Validate the GitLab CI scripts against the schema. Doesn't catch everything but helps
  - id: check-gitlab-ci

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks: []
  # Identify common spelling mistakes in code and comments
  # - id: codespell
